### ISSUE TITLE
add option for simply converting all VCF rows into mutations

### ISSUE THREAD

**Issue by philipwfowler** [philipwfowler/piezo#2]
i.e. ignore any catalogue and simply work out if each variant occurs in a CDS (or promoter) and report as normally.

**Comment by philipwfowler** [comment]
The code below preferentially pulls out all genes in the Genbank file. If a record is not marked as a `gene`, but is still marked as a `locus_tag` then it is added to the list. This results in 3,909 entries from v3 of H37rV split between 1,913 genes and 1,996 locus tags.

```
from Bio import SeqIO

reference_genome=SeqIO.read("/Users/fowler/packages/piezo/config/H37rV_v3.gbk",'genbank')

gene_panel=[]

for record in reference_genome.features:
    if record.type in ['CDS','rRNA']:
        if 'gene' in record.qualifiers.keys():
            gene_name=record.qualifiers['gene'][0]
        elif 'locus_tag' in record.qualifiers.keys():
            gene_name=record.qualifiers['locus_tag'][0]
        else:
            continue
        
        gene_panel.append(gene_name)

print(len(gene_panel))
```

I need to know if this is close enough to "all genes"?

**Comment by rob-shaw** [comment]
From what little I understand, I can't think of anything missed as you here gathering up all GenBank flagged loci.

**Comment by philipwfowler** [comment]
fixed in rewrite
